const Head = () => (
  <>
    <title>Create Next App</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="descrisption" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </>
);

export default Head;
